=begin
#SendinBlue API

#SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 

OpenAPI spec version: 3.0.0
Contact: contact@sendinblue.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'spec_helper'
require 'json'

# Unit tests for SibApiV3Sdk::CRMApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CRMApi' do
  before do
    # run before each test
    @instance = SibApiV3Sdk::CRMApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CRMApi' do
    it 'should create an instance of CRMApi' do
      expect(@instance).to be_instance_of(SibApiV3Sdk::CRMApi)
    end
  end

  # unit tests for crm_files_id_data_get
  # Get file details
  # @param id File id to get file data.
  # @param [Hash] opts the optional parameters
  # @return [FileData]
  describe 'crm_files_id_data_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_files_id_delete
  # Delete a file
  # @param id File id to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'crm_files_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_files_id_get
  # Download a file
  # @param id File id to download.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'crm_files_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_files_post
  # Upload a file
  # @param file File data to create a file.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :deals_ids Deal ids linked to a file
  # @return [FileData]
  describe 'crm_files_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_notes_id_delete
  # Delete a note
  # @param id Note ID to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'crm_notes_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_notes_id_get
  # Get a note
  # @param id Note ID to get
  # @param [Hash] opts the optional parameters
  # @return [Note]
  describe 'crm_notes_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_notes_id_patch
  # Update a note
  # @param id Note ID to update
  # @param body Note data to update a note
  # @param [Hash] opts the optional parameters
  # @return [Note]
  describe 'crm_notes_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_notes_post
  # Create a note
  # @param body Note data to create a note.
  # @param [Hash] opts the optional parameters
  # @return [Note]
  describe 'crm_notes_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_tasks_id_delete
  # Delete a task
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'crm_tasks_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_tasks_id_get
  # Get a task
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'crm_tasks_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_tasks_id_patch
  # Update a task
  # @param id 
  # @param body Updated task details.
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'crm_tasks_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_tasks_post
  # Create a task
  # @param body Task name.
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'crm_tasks_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for crm_tasktypes_get
  # Get all task types
  # @param [Hash] opts the optional parameters
  # @return [TaskTypes]
  describe 'crm_tasktypes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
